apiVersion: apps/v1
kind: Deployment
metadata:
  name: rachit-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rachit-myapp
  template:
    metadata:
      labels:
        app: rachit-myapp
    spec:
     containers:
      - name: rachit-myapp-container
        image: nginx
        ports:
        - containerPort: 80
