apiVersion: v1
kind: Service
metadata:
  name: rachit-myapp-service
spec:
  type: NodePort
  selector:
    app: rachit-myapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007